### ISSUE TITLE
Quoted strings can contain spaces

### ISSUE THREAD

**Issue by gene-hightower** [skeggse/isemail#213]
# What / Why

Valid quoted strings including a space in the local-part don't validate.

According to RFC-5321 section 4.1.2 quoted strings can contain "any ASCII graphic or space" [...] "except double-quote and the backslash itself" -- so spaces should be just fine.

## When

```
$ node
Welcome to Node.js v14.16.0.
Type ".help" for more information.
> var Isemail = require('isemail');
undefined
> Isemail.validate('test@iana.org');
true
> Isemail.validate('"one two"@iana.org');
false
> Isemail.validate('"one.two"@iana.org');
true
> 

```

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

RFC-5321 allows lots of characters in quoted strings including ASCII space.

## Who

* n/a

## References

<https://tools.ietf.org/html/rfc5321>

**Comment by skeggse** [comment]
I'm behind on GitHub issues, sorry. This is configurable in `isemail`, because while it's valid it's also unusual. If you want to support that, pass `errorLevel: Isemail.diagnoses.rfc5321QuotedString` (or `Isemail.diagnoses.rfc5321AddressLiteral` for all unusual elements).

I'll also note that I cannot reply to you because Gmail thinks your email address (which contains spaces) is invalid:
![image](https://user-images.githubusercontent.com/1348991/112067449-4f92be80-8b25-11eb-9ecb-2f8226990bf7.png)

**Comment by gene-hightower** [comment]
Yes, Gmail will deliver a message with that From: address, but you can't reply. They fail on quoted strings in the local-part. See <https://digilicious.com/mail.html>
